[package]
name = "vizir-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "=0.11.0"
vizir-core = { path = "../vizir-core" }
vizir-backend-svg = { path = "../vizir-backend-svg" }

[dev-dependencies]
roxmltree = "0.21.1"
