#!/usr/bin/env python3
"""Poison-pill battery (2026-09-07 audit hardening, class no-poison).

Every gate must prove it can bite: one positive control per ban class is
injected into a THROWAWAY /tmp copy of the corpus (never the frozen layer
and never this tree), the gate must flag it, and the clean corpus must
yield zero. Run record lands in data/audit/pills.json (fingerprint-exempt
audit location, see VERIFICATION §13).

Pill classes:
  build.py code-detail gate (six sweeps + banned identifier):
    1 file:line coordinate      2 engine source filename
    3 N-M line range            4 第N行
    5 source keyword            6 identifier call string (visible text)
    7 banned identifier
  build.py claims gate:         8 claim id E1 removed from page
  build.py digit sweep gate:    9 hand-typed number 987654
  svg-linter gate:             10 dangling local reference (defs id deleted)
                              11 duplicate XML id
Controls: clean build exit 0; resolved-reference svg exit 0; all 13
svg/*.svg exit 0 with zero findings.

Usage: python3 tools/poison_pills.py   (exit 0 iff every pill bites and
every control is clean)
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path

TREE = Path(__file__).resolve().parent.parent
LINTER = Path("/Users/junix/projects/plot/svg-linter/target/release/svg-linter")
WORK = Path("/tmp/vizir-explainer-pills")
AUDIT = TREE / "data" / "audit"

# Injected into the hero src_note of a copy of panels.py (reader-visible
# text, so every sweep class sees it). One pill per class.
DETAIL_PILLS = [
    ("file:line coordinate", "capability.rs:152",
     "code-detail file:line coordinate"),
    ("engine source filename", "patch.rs",
     "code-detail engine filename patch.rs"),
    ("N-M line range", ":77-82", "code-detail N–M line range"),
    ("第N行", "第 312 行", "code-detail 第N行"),
    ("source keyword", "impl", "code-detail source keyword"),
    ("identifier call string (visible)", "frob(42)",
     "code-detail identifier call string"),
    ("banned identifier", "diff_scene",
     "code-detail identifier 'diff_scene'"),
]
HERO_NOTE_ANCHOR = '"fresh clone 复现为 10"))'


def fresh_copy(name: str) -> Path:
    d = WORK / name
    if d.exists():
        shutil.rmtree(d)
    d.mkdir(parents=True)
    for f in ["build.py", "panels.py", "svgkit.py"]:
        shutil.copy2(TREE / f, d / f)
    shutil.copytree(TREE / "data", d / "data",
                    ignore=shutil.ignore_patterns("audit"))
    return d


def inject_note(copy: Path, pill_text: str) -> None:
    p = copy / "panels.py"
    s = p.read_text()
    assert HERO_NOTE_ANCHOR in s, "hero src_note anchor moved in panels.py"
    p.write_text(s.replace(
        HERO_NOTE_ANCHOR,
        f'"fresh clone 复现为 10 · 毒丸 {pill_text}"))'))


def run_build(copy: Path) -> tuple[int, str]:
    r = subprocess.run(
        [sys.executable, "-B", "build.py"], cwd=copy,
        capture_output=True, text=True)
    return r.returncode, (r.stderr + r.stdout)


def run_linter(svg: Path) -> tuple[int, str, int]:
    r = subprocess.run(
        [str(LINTER), "check", "--plain", "--require-complete", str(svg)],
        capture_output=True, text=True)
    findings = [ln for ln in r.stdout.splitlines()
                if ln.startswith("finding\t")]
    return r.returncode, r.stdout, len(findings)


def main() -> int:
    if not LINTER.exists():
        print(f"FATAL: svg-linter binary missing: {LINTER}", file=sys.stderr)
        return 2
    if WORK.exists():
        shutil.rmtree(WORK)
    WORK.mkdir(parents=True)
    results: list[dict] = []
    ok = True

    def record(cls, injected, expect, rc, caught, note=""):
        nonlocal ok
        good = caught
        ok = ok and good
        results.append({"pill": cls, "injected": injected,
                        "expect_gate_to_flag": expect,
                        "exit_code": rc, "caught": good, "note": note})

    # ---- build.py gate pills ------------------------------------------------
    for i, (cls, pill, expect) in enumerate(DETAIL_PILLS, 1):
        copy = fresh_copy(f"detail-{i}")
        inject_note(copy, pill)
        rc, out = run_build(copy)
        record(cls, pill, expect, rc, rc == 1 and expect in out)

    # claims gate pill: remove claim id E1 from the page — every E1 chip
    # lives in panels.py (registry rows + src_note pointers) except the
    # footer's 「声明 E1–E6」 line, which is generated by build.py itself;
    # poison both so E1 disappears from the whole page.
    copy = fresh_copy("claims")
    p = copy / "panels.py"
    p.write_text(p.read_text().replace("E1", "E7"))
    b = copy / "build.py"
    b.write_text(b.read_text().replace("声明 E1–E6", "声明 E7–E6"))
    rc, out = run_build(copy)
    record("claim id binding (E1 removed from page)", "E1 -> E7",
           "claim id E1: missing from page text", rc,
           rc == 1 and "claim id E1: missing from page text" in out
           and "claim id E7" in out)

    # digit sweep pill: hand-typed number that exists nowhere in data/*.json
    copy = fresh_copy("digit")
    inject_note(copy, "987654")
    rc, out = run_build(copy)
    record("digit sweep (unclaimed number)", "987654",
           "digit sweep: unclaimed token '987654'", rc,
           rc == 1 and "digit sweep: unclaimed token '987654'" in out)

    # clean control: unmodified copy must build green (all gates 0 hits)
    copy = fresh_copy("clean")
    rc, out = run_build(copy)
    record("CONTROL clean build (all build gates zero)", "(none)",
           "exit 0", rc, rc == 0,
           note=out.strip().splitlines()[-1] if out.strip() else "")

    # ---- svg-linter pills ---------------------------------------------------
    src = (TREE / "svg" / "01-hero.svg").read_text()
    defs = ('<defs><linearGradient id="pill-grad">'
            '<stop offset="0" stop-color="#356A79"/>'
            '</linearGradient></defs>')
    i0 = src.index(">", src.index("<svg")) + 1
    base = src[:i0] + defs + src[i0:]
    base = base.replace('fill="#FDFBF7"', 'fill="url(#pill-grad)"', 1)
    assert 'url(#pill-grad)' in base, "reference anchor missing in 01-hero"

    lab = WORK / "linter"
    lab.mkdir()
    (lab / "with-def.svg").write_text(base)                     # control
    (lab / "dangling.svg").write_text(
        base.replace('id="pill-grad"', 'id="pill-gone"'))       # pill 10
    (lab / "duplicate.svg").write_text(
        base.replace("</defs>", '<linearGradient id="pill-grad"/></defs>'))

    rc, out, n = run_linter(lab / "with-def.svg")
    record("CONTROL resolved reference (defs id present)",
           "defs id pill-grad + url(#pill-grad)", "exit 0, 0 findings",
           rc, rc == 0 and n == 0, note=f"findings={n}")

    rc, out, n = run_linter(lab / "dangling.svg")
    record("svg-linter dangling reference (defs id deleted)",
           "id pill-grad -> pill-gone, url(#pill-grad) kept",
           "svg/dangling-reference", rc,
           rc != 0 and "svg/dangling-reference" in out, note=f"findings={n}")

    rc, out, n = run_linter(lab / "duplicate.svg")
    record("svg-linter duplicate id",
           "second linearGradient id=pill-grad",
           "svg/duplicate-id", rc,
           rc != 0 and "svg/duplicate-id" in out, note=f"findings={n}")

    # clean control: the real 13 svg files, zero findings each
    clean_svgs = True
    for f in sorted((TREE / "svg").glob("*.svg")):
        rc, out, n = run_linter(f)
        if rc != 0 or n != 0:
            clean_svgs = False
            record("CONTROL clean corpus", f.name, "exit 0, 0 findings",
                   rc, False, note=f"findings={n}")
    if clean_svgs:
        record("CONTROL clean corpus (13 svg files)", "(none)",
               "exit 0, 0 findings each", 0, True, note="13 files, 0 findings")

    # ---- run record ---------------------------------------------------------
    pills = [r for r in results if not r["pill"].startswith("CONTROL")]
    controls = [r for r in results if r["pill"].startswith("CONTROL")]
    doc = {
        "battery": "poison-pills",
        "date": date.today().isoformat(),
        "workdir": str(WORK),
        "summary": {
            "pills_total": len(pills),
            "pills_caught": sum(1 for r in pills if r["caught"]),
            "controls_total": len(controls),
            "controls_clean": sum(1 for r in controls if r["caught"]),
        },
        "results": results,
    }
    AUDIT.mkdir(exist_ok=True)
    (AUDIT / "pills.json").write_text(
        json.dumps(doc, ensure_ascii=False, indent=1) + "\n")

    for r in results:
        tag = "PASS" if r["caught"] else "FAIL"
        print(f"[{tag}] {r['pill']} (exit {r['exit_code']})")
    s = doc["summary"]
    print(f"pills: {s['pills_caught']}/{s['pills_total']} caught, "
          f"controls: {s['controls_clean']}/{s['controls_total']} clean "
          f"-> {AUDIT / 'pills.json'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
